#!/bin/bash

if [ "$1" != "" ]; then
    mkdir ${1}
    cd ${1}
    npm init -y
    arguments=($@)
    for (( package=1; package<$#; package++ )); do
        npm i ${arguments[package]} -S
    done
    touch index.js
    mkdir server client tests 
    git init
    echo "Done 🔥"
    exit 0
else
    echo "Please supply a name for your project"
    exit 64
fi
